import { parallaxMouse } from './parallax-mouse.js'

parallaxMouse({ elements: '.parallax__title', moveFactor: 20, wrap: '.parallax', perspective: '100px' })
parallaxMouse({ elements: '.coubs__item-1', moveFactor: 20, wrap: '.parallax', perspective: '400px' })
parallaxMouse({ elements: '.coubs__item-2', moveFactor: 10, wrap: '.parallax', perspective: '400px' })
parallaxMouse({ elements: '.coubs__item-3', moveFactor: 50, wrap: '.parallax', perspective: '400px' })
parallaxMouse({ elements: '.coubs__item-4', moveFactor: 10, wrap: '.parallax', perspective: '400px' })
parallaxMouse({ elements: '.coubs__item-5', moveFactor: 20, wrap: '.parallax', perspective: '400px' })
parallaxMouse({ elements: '.coubs__item-6', moveFactor: 50, wrap: '.parallax', perspective: '400px' })
parallaxMouse({ elements: '.coubs__item-7', moveFactor: 20, wrap: '.parallax', perspective: '400px' })
parallaxMouse({ elements: '.coubs__item-8', moveFactor: 25, wrap: '.parallax', perspective: '400px' })
parallaxMouse({ elements: '.coubs__item-9', moveFactor: 70, wrap: '.parallax', perspective: '400px' })
parallaxMouse({ elements: '.coubs__item-10', moveFactor: 20, wrap: '.parallax', perspective: '400px' })
parallaxMouse({ elements: '.coubs__item-11', moveFactor: 20, wrap: '.parallax', perspective: '400px' })
parallaxMouse({ elements: '.coubs__item-12', moveFactor: 30, wrap: '.parallax', perspective: '400px' })
parallaxMouse({ elements: '.coubs__item-13', moveFactor: 10, wrap: '.parallax', perspective: '400px' })
parallaxMouse({ elements: '.coubs__item-14', moveFactor: 20, wrap: '.parallax', perspective: '400px' })
parallaxMouse({ elements: '.coubs__item-15', moveFactor: 10, wrap: '.parallax', perspective: '400px' })
parallaxMouse({ elements: '.coubs__item-16', moveFactor: 70, wrap: '.parallax', perspective: '400px' })
parallaxMouse({ elements: '.coubs__item-17', moveFactor: 50, wrap: '.parallax', perspective: '400px' })
parallaxMouse({ elements: '.coubs__item-18', moveFactor: 20, wrap: '.parallax', perspective: '400px' })
parallaxMouse({ elements: '.coubs__item-19', moveFactor: 10, wrap: '.parallax', perspective: '400px' })
parallaxMouse({ elements: '.coubs__item-20', moveFactor: 50, wrap: '.parallax', perspective: '400px' })
parallaxMouse({ elements: '.coubs__item-21', moveFactor: 70, wrap: '.parallax', perspective: '400px' })
parallaxMouse({ elements: '.coubs__item-22', moveFactor: 50, wrap: '.parallax', perspective: '400px' })
parallaxMouse({ elements: '.coubs__item-23', moveFactor: 10, wrap: '.parallax', perspective: '400px' })
parallaxMouse({ elements: '.coubs__item-24', moveFactor: 15, wrap: '.parallax', perspective: '400px' })
parallaxMouse({ elements: '.coubs__item-25', moveFactor: 20, wrap: '.parallax', perspective: '400px' })